### ISSUE TITLE
Database Connection Setup Failing with MySQL

### ISSUE THREAD

**Issue by martin-martin** [moodlehq/moodle-docker#138] opened 2020-10-01 09:31 UTC
When attempting to [set up a local Moodle dev environment](https://github.com/moodlehq/moodle-docker#quick-start) using `moodle-docker` and `mysql` as the Database server, I run into the following issue:

![image](https://user-images.githubusercontent.com/12371494/94792327-7e836f80-03e1-11eb-9494-8266d3c9514d.png)

This happens after I try to start the PHP site on the `webserver` container for manual testing, [as described here](https://github.com/moodlehq/moodle-docker#use-containers-for-manual-testing), and navigating to `localhost:8000`.

---

I have tested the same setup with using PostgreSQL as the database server, only changing the `export MOODLE_DOCKER_DB=pgsql` (instead of `mysql`) which makes the development server work as expected and I am able to access the Moodle site.

Is there any additional package missing that breaks the connection to MySQL?

**Comment by martin-martin** [comment] 2020-10-01 09:34
Here are the last few lines when running `docker-compose up` without `-d`:

```
db_1         | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1         | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
db_1         | 2020-10-01 09:32:54+00:00 [Note] [Entrypoint]: Creating database moodle
db_1         | 2020-10-01 09:32:54+00:00 [Note] [Entrypoint]: Creating user moodle
db_1         | 2020-10-01 09:32:54+00:00 [Note] [Entrypoint]: Giving user moodle access to schema moodle
db_1         | 
db_1         | 2020-10-01 09:32:54+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/dump.sql
db_1         | ERROR: Can't initialize batch_readline - may be the input source is a directory or a block device.
moodle-docker_db_1 exited with code 1
```

Would appreciate any help and pointers on this

**Comment by stronk7** [comment] 2020-10-01 09:50
Hi @martin-martin ,

I've tried here just with:

````
$ export MOODLE_DOCKER_WWWROOT=/Users/stronk7/git_moodle/ci-tests
$ export MOODLE_DOCKER_DB=mysql
$ cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php
$ bin/moodle-docker-compose up -d
Creating network "moodle-docker_default" with the default driver
Creating moodle-docker_exttests_1  ... done
Creating moodle-docker_selenium_1  ... done
Creating moodle-docker_mailhog_1  ... done
Creating moodle-docker_db_1       ... done
Creating moodle-docker_webserver_1 ... done
$ docker logs moodle-docker_db_1
...
...
2020-10-01T09:41:04.862668Z 0 [Note] mysqld: ready for connections.
Version: '5.7.31'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
````

So everything seems to be working ok. A couple of things to try, that I can imagine could be:
1) Ensure you're using the last moodle-docker checkout. git fetch/pull changes if needed.
2) Ensure that there isn't any incorrect mysql image being used, docker always tries with local images and, if there is any matching the name and tag it will be get precedence. Surely the easiest is to stop all your containers and then perform a `docker system prune -a -f --volumes` note that will remove everything (images, volumes, networks...), *in case you've persistent stuff around that you want to preserve don't use it!!*. But will also cause the correct mysql image to be used (fetched from docker hub).

Other than that I cannot imagine the problem, are you on unix? mac? windows?

**Comment by martin-martin** [comment] 2020-10-01 10:01
Hi @stronk7 thanks for your quick answer!

- **OS**: Working on MacOS Catalina 10.15.6 (19G2021)
- **Repo**: I pulled the latest version of `moodle-docker` before trying this
- **MySQL Docker**: I didn't have any local `mysql` Docker images before running the command (the relevant MySQL image got pulled when I ran it) Just recently deleted all my old Docker images because I ran out of space 😅 

I _do_ have a local installation of MySQL on my system, but don't really expect that to interfere, considering that everything is run in Docker images?

**Comment by martin-martin** [comment] 2020-10-01 10:06
I don't know how everything here interacts, but I was looking at this line:

```
db_1         | 2020-10-01 09:32:54+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/dump.sql
db_1         | ERROR: Can't initialize batch_readline - may be the input source is a directory or a block device.
moodle-docker_db_1 exited with code 1
```

And I did find that `dump.sql` inside of the main `moodle-docker` folder is indeed a _folder_. Which is probably perfectly fine, considering also that all works well with PostgreSQL, just thought I'd mention it because the error message specifically refers to something called `dump.sql` and expects it not to be a folder. Which would make sense to me if it would contain some sort of setup script for the database.

**Comment by stronk7** [comment] 2020-10-01 10:14
Aha, I'm a Mac too (also with Catalina 10.15.6). Using Docker Desktop 2.3.0.4

I've executed here the `docker system prune -a -f --volumes` command commented above, to force everything to be pulled and everything finished ok, with MySQL up and running (without any line in the logs mentioning any `dump.sql`). Neither there is a `dump.sql` within moodle-docker, so that's confusing me.

Also, have confirmed that we don't do anything special with MySQL, but just use the official images as they are.

Just guessing if it can be something in your docker configuration (shared resources or virtual disk size...). Apart from that cannot imagine much.

CIao :-)

**Comment by martin-martin** [comment] 2020-10-01 10:59
Strange! I wonder what this folder is about and why I have it 🤔 

```zsh
➜  moodle-docker git:(master) ✗ git pull
Already up to date.
➜  moodle-docker git:(master) ✗ ls
README.md                     config.docker-template.php    db.mysql.yml                  moodle-app.yml                service.mail.yml
assets                        db.mariadb.yml                db.oracle.yml                 phpunit-external-services.yml tests
base.yml                      db.mssql.5.6.yml              dump.sql                      selenium.chrome.yml           volumes-cached.yml
bin                           db.mssql.yml                  moodle-app-dev.yml            selenium.debug.yml            webserver.port.yml
➜  moodle-docker git:(master) ✗ cd dump.sql 
➜  dump.sql git:(master) ✗ ls
➜  dump.sql git:(master) ✗ ls -al
total 0
drwxr-xr-x   2 martin  staff   64 Oct  1 11:34 .
drwxr-xr-x  26 martin  staff  832 Oct  1 11:34 ..
➜  dump.sql git:(master) ✗ 
```

I'll try to play around some more and post here if I manage to work it out. Thanks.

**Comment by vsotirasqmplus** [comment] 2020-10-09 16:25
If by coincidence you are on CEntOS 8 then read  [here](https://github.com/moodlehq/moodle-docker/issues/140#issuecomment-706272776)

**Comment by stronk7** [comment] 2020-10-22 21:35
Did you manage to solve your problem, @martin-martin ? I'm thinking to close this as far as everything seems to be working ok and it seems to be some "local-glitch" your side.

**Comment by martin-martin** [comment] 2020-10-23 13:06
I didn't manage to get it running using mysql, still not sure why. I ended
up using the [MAMP Installer](https://download.moodle.org/macosx/) for
MacOS instead, and that has worked for me. No docker, but it's fine for
what I need it right now.
.

**Comment by stronk7** [comment] 2020-10-24 07:29
Thanks Martin!

**Closed by stronk7** 2020-10-24 07:29 UTC
